# Generated by infra-x v<version>
# Stack: aws-lambda-api
# Blueprint: aws-lambda-api
# Description: Pay-per-use REST API on Lambda + API Gateway HTTP API, backed by a DynamoDB on-demand table.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "aws_iam_role" "lambda_role" {
  name               = "${var.api_name}-${var.environment}-exec"
  assume_role_policy = <<-EOT
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": { "Service": "lambda.amazonaws.com" },
    "Action": "sts:AssumeRole"
  }]
}

EOT
}

resource "aws_iam_role_policy_attachment" "lambda_basic_exec" {
  role       = aws_iam_role.lambda_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy" "lambda_dynamodb_policy" {
  name   = "${var.api_name}-dynamodb-rw"
  role   = aws_iam_role.lambda_role.id
  policy = <<-EOT
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": [
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:UpdateItem",
      "dynamodb:DeleteItem",
      "dynamodb:Query",
      "dynamodb:Scan"
    ],
    "Resource": "${aws_dynamodb_table.api_table.arn}"
  }]
}

EOT
}
