# Generated by infra-x v<version>
# Stack: aws-lambda-api
# Blueprint: aws-lambda-api
# Description: Pay-per-use REST API on Lambda + API Gateway HTTP API, backed by a DynamoDB on-demand table.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "aws_cloudwatch_log_group" "api_log_group" {
  name              = "/aws/lambda/${aws_lambda_function.api_handler.function_name}"
  retention_in_days = 14
}
