# Generated by infra-x v<version>
# Stack: aws-lambda-api
# Blueprint: aws-lambda-api
# Description: Pay-per-use REST API on Lambda + API Gateway HTTP API, backed by a DynamoDB on-demand table.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

output "api_url" {
  value       = aws_apigatewayv2_api.api_gateway.api_endpoint
  description = "Public HTTPS endpoint for the API"
}

output "table_name" {
  value       = aws_dynamodb_table.api_table.name
  description = "DynamoDB table name (also injected as TABLE_NAME env var)"
}

output "lambda_log_group" {
  value       = aws_cloudwatch_log_group.api_log_group.name
  description = "CloudWatch log group for the Lambda"
}
