# Generated by infra-x v<version>
# Stack: aws-lambda-api
# Blueprint: aws-lambda-api
# Description: Pay-per-use REST API on Lambda + API Gateway HTTP API, backed by a DynamoDB on-demand table.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.4"
    }
  }
}
