# Generated by infra-x v<version>
# Stack: aws-s3-static-site
# Blueprint: aws-s3-static-site
# Description: Fast, global static website with automatic HTTPS via CloudFront and an S3 origin (private bucket served through OAC).
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "aws_cloudfront_distribution" "cdn" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  price_class         = "PriceClass_100"
  tags                = {
    Name        = "${var.site_name}-cdn"
    Environment = var.environment
    ManagedBy   = "infra-x"
  }

  origin {
    domain_name              = aws_s3_bucket.site_bucket.bucket_regional_domain_name
    origin_id                = "${var.site_name}-s3-origin"
    origin_access_control_id = aws_cloudfront_origin_access_control.site_oac.id
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "${var.site_name}-s3-origin"
    viewer_protocol_policy = "redirect-to-https"
    compress               = true

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }
  }

  restrictions {

    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
