# Generated by infra-x v<version>
# Stack: aws-s3-static-site
# Blueprint: aws-s3-static-site
# Description: Fast, global static website with automatic HTTPS via CloudFront and an S3 origin (private bucket served through OAC).
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

output "cloudfront_domain_name" {
  value       = aws_cloudfront_distribution.cdn.domain_name
  description = "The CloudFront distribution URL (use this as your CNAME target)"
}

output "bucket_name" {
  value       = aws_s3_bucket.site_bucket.id
  description = "The S3 bucket name where you upload your site files"
}
