# Generated by infra-x v<version>
# Stack: aws-s3-static-site
# Blueprint: aws-s3-static-site
# Description: Fast, global static website with automatic HTTPS via CloudFront and an S3 origin (private bucket served through OAC).
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

provider "aws" {
  region = "us-east-1"
}
