# Generated by infra-x v<version>
# Stack: aws-s3-static-site
# Blueprint: aws-s3-static-site
# Description: Fast, global static website with automatic HTTPS via CloudFront and an S3 origin (private bucket served through OAC).
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

variable "site_name" {
  type        = string
  description = "Globally unique S3 bucket name for the site"

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$", var.site_name))
    error_message = "site_name must be 3-63 chars, lowercase letters/digits/hyphens, and start+end with a letter or digit (S3 bucket naming rules)."
  }
}

variable "environment" {
  type        = string
  description = "Environment label"
  default     = "prod"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of dev, staging, prod."
  }
}

variable "aws_region" {
  type        = string
  description = "AWS region for the bucket"
  default     = "us-east-1"

  validation {
    condition     = can(regex("^[a-z]{2}-[a-z]+-[0-9]+$", var.aws_region))
    error_message = "aws_region must look like an AWS region (e.g. us-east-1, eu-west-2)."
  }
}
