"""
Snapshot tests — pin every blueprint's rendered output to a known-good fixture.

Catches accidental renderer regressions: if you tweak _render_value or the
file-split logic and an existing blueprint now emits different HCL, this test
fails loudly with a diff.

Workflow
--------
- First run / new blueprint: set INFRAX_UPDATE_SNAPSHOTS=1, run pytest, commit
  the resulting tests/snapshots/<bp_id>/* files.
- Day-to-day: just run pytest. If something legitimately changed and you've
  reviewed the diff, re-run with INFRAX_UPDATE_SNAPSHOTS=1 to update.

We deliberately ignore the auto-generated header line that contains the
infra-x version, otherwise every version bump would invalidate every snapshot.
"""

from __future__ import annotations

import difflib
import os
import re
from pathlib import Path

import pytest

from infra_x.agent.planner import Planner
from infra_x.blueprints.loader import load_blueprint
from infra_x.render import HCLRenderer

ALL_BLUEPRINTS = [
    "aws-s3-static-site",
    "aws-lambda-api",
    "aws-ecs-fargate-web",
    "gcp-cloud-run",
    "aws-eks-cluster",
]

SNAPSHOT_DIR = Path(__file__).parent / "snapshots"
UPDATE = os.environ.get("INFRAX_UPDATE_SNAPSHOTS") == "1"

# Strip the version line so snapshots survive version bumps.
_VERSION_LINE = re.compile(r"^# Generated by infra-x v\S+\n", re.MULTILINE)


def _normalize(content: str) -> str:
    return _VERSION_LINE.sub("# Generated by infra-x v<version>\n", content)


@pytest.mark.parametrize("bp_id", ALL_BLUEPRINTS)
def test_blueprint_snapshot(bp_id: str) -> None:
    bp = load_blueprint(bp_id)
    stack = Planner(llm=None).deterministic(bp, stack_name=bp_id).stack
    files = HCLRenderer(stack).files()

    snap_dir = SNAPSHOT_DIR / bp_id

    if UPDATE:
        snap_dir.mkdir(parents=True, exist_ok=True)
        # Clean up files that no longer exist
        for existing in snap_dir.glob("*"):
            if existing.name not in files:
                existing.unlink()
        for name, content in files.items():
            (snap_dir / name).write_text(_normalize(content))
        return

    if not snap_dir.exists():
        pytest.fail(
            f"No snapshot found for {bp_id}. Create one with:\n"
            f"  INFRAX_UPDATE_SNAPSHOTS=1 pytest tests/test_snapshots.py::test_blueprint_snapshot[{bp_id}]"
        )

    actual_names = set(files.keys())
    expected_names = {p.name for p in snap_dir.glob("*")}
    assert actual_names == expected_names, (
        f"{bp_id}: file set differs.\n"
        f"  expected: {sorted(expected_names)}\n"
        f"  actual:   {sorted(actual_names)}\n"
        "If intentional, refresh with INFRAX_UPDATE_SNAPSHOTS=1 pytest"
    )

    diffs: list[str] = []
    for name, content in files.items():
        expected = (snap_dir / name).read_text()
        actual = _normalize(content)
        if expected != actual:
            diff = "".join(
                difflib.unified_diff(
                    expected.splitlines(keepends=True),
                    actual.splitlines(keepends=True),
                    fromfile=f"snapshot/{bp_id}/{name}",
                    tofile=f"actual/{bp_id}/{name}",
                )
            )
            diffs.append(diff)

    if diffs:
        msg = (
            f"{bp_id}: rendered output differs from snapshot.\n"
            "If intentional, refresh with: INFRAX_UPDATE_SNAPSHOTS=1 pytest\n\n"
            + "\n".join(diffs[:3])  # cap output to first 3 diffs to keep CI logs readable
        )
        pytest.fail(msg)
