# Generated by infra-x v<version>
# Stack: aws-ecs-fargate-web
# Blueprint: aws-ecs-fargate-web
# Description: Container web app on ECS Fargate behind an Application Load Balancer in a 2-AZ VPC. Minimal but production-shaped.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "aws_cloudwatch_log_group" "task_logs" {
  name              = "/ecs/${var.app_name}"
  retention_in_days = 14
}
