# Generated by infra-x v<version>
# Stack: aws-ecs-fargate-web
# Blueprint: aws-ecs-fargate-web
# Description: Container web app on ECS Fargate behind an Application Load Balancer in a 2-AZ VPC. Minimal but production-shaped.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

output "alb_dns_name" {
  value       = aws_lb.alb.dns_name
  description = "ALB DNS name (point your CNAME here)"
}

output "cluster_name" {
  value       = aws_ecs_cluster.cluster.name
}
