# Generated by infra-x v<version>
# Stack: aws-ecs-fargate-web
# Blueprint: aws-ecs-fargate-web
# Description: Container web app on ECS Fargate behind an Application Load Balancer in a 2-AZ VPC. Minimal but production-shaped.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

variable "app_name" {
  type        = string

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{1,30}[a-z0-9]$", var.app_name))
    error_message = "app_name must be 3-32 chars, lowercase letters/digits/hyphens."
  }
}

variable "aws_region" {
  type        = string
  default     = "us-east-1"

  validation {
    condition     = can(regex("^[a-z]{2}-[a-z]+-[0-9]+$", var.aws_region))
    error_message = "aws_region must look like an AWS region (e.g. us-east-1)."
  }
}

variable "container_image" {
  type        = string
  default     = "public.ecr.aws/nginx/nginx:latest"
}

variable "container_port" {
  type        = number
  default     = 80

  validation {
    condition     = var.container_port >= 1 && var.container_port <= 65535
    error_message = "container_port must be between 1 and 65535."
  }
}

variable "desired_count" {
  type        = number
  default     = 2

  validation {
    condition     = var.desired_count >= 1
    error_message = "desired_count must be >= 1."
  }
}

variable "cpu" {
  type        = number
  default     = 512

  validation {
    condition     = contains([256, 512, 1024, 2048, 4096, 8192, 16384], var.cpu)
    error_message = "cpu must be one of 256, 512, 1024, 2048, 4096, 8192, 16384 (Fargate-supported values)."
  }
}

variable "memory" {
  type        = number
  default     = 1024

  validation {
    condition     = var.memory >= 512 && var.memory <= 122880
    error_message = "memory must be between 512 and 122880 MB (Fargate range). See AWS docs for valid CPU/memory combinations."
  }
}
