# Generated by infra-x v<version>
# Stack: aws-ecs-fargate-web
# Blueprint: aws-ecs-fargate-web
# Description: Container web app on ECS Fargate behind an Application Load Balancer in a 2-AZ VPC. Minimal but production-shaped.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
