# Generated by infra-x v<version>
# Stack: gcp-cloud-run
# Blueprint: gcp-cloud-run
# Description: Serverless containerized HTTP service on Cloud Run with an Artifact Registry repo for the image.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "google_cloud_run_v2_service" "run_service" {
  name     = var.service_name
  location = var.region
  ingress  = "INGRESS_TRAFFIC_ALL"

  template {
    service_account = google_service_account.run_sa.email

    scaling {
      min_instance_count = var.min_instances
      max_instance_count = var.max_instances
    }

    containers {
      image = var.container_image

      ports {
        container_port = 8080
      }

      resources {
        limits   = {
          cpu    = "1"
          memory = "512Mi"
        }
        cpu_idle = true
      }

      env {
        name  = "PORT"
        value = "8080"
      }
    }
  }
}
