# Generated by infra-x v<version>
# Stack: gcp-cloud-run
# Blueprint: gcp-cloud-run
# Description: Serverless containerized HTTP service on Cloud Run with an Artifact Registry repo for the image.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "google_service_account" "run_sa" {
  account_id   = "${var.service_name}-run"
  display_name = "Service account for ${var.service_name} Cloud Run service"
}

resource "google_cloud_run_v2_service_iam_member" "run_invoker_public" {
  project  = var.project_id
  location = google_cloud_run_v2_service.run_service.location
  name     = google_cloud_run_v2_service.run_service.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}
