# Generated by infra-x v<version>
# Stack: gcp-cloud-run
# Blueprint: gcp-cloud-run
# Description: Serverless containerized HTTP service on Cloud Run with an Artifact Registry repo for the image.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

output "service_url" {
  value       = google_cloud_run_v2_service.run_service.uri
  description = "Public HTTPS URL of the Cloud Run service"
}

output "artifact_repo_url" {
  value       = "${var.region}-docker.pkg.dev/${var.project_id}/${google_artifact_registry_repository.artifact_repo.repository_id}"
  description = "Push your container images to this registry path"
}
