# Generated by infra-x v<version>
# Stack: gcp-cloud-run
# Blueprint: gcp-cloud-run
# Description: Serverless containerized HTTP service on Cloud Run with an Artifact Registry repo for the image.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

variable "project_id" {
  type        = string
  description = "GCP project ID"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{4,28}[a-z0-9]$", var.project_id))
    error_message = "project_id must be 6-30 chars, lowercase letters/digits/hyphens (GCP project ID rules)."
  }
}

variable "service_name" {
  type        = string
  description = "Cloud Run service name"

  validation {
    condition     = can(regex("^[a-z]([a-z0-9-]{0,47}[a-z0-9])?$", var.service_name))
    error_message = "service_name must be 1-49 chars, lowercase letters/digits/hyphens, start with a letter (Cloud Run rules)."
  }
}

variable "region" {
  type        = string
  default     = "us-central1"
}

variable "container_image" {
  type        = string
  description = "Container image URI (placeholder until first build)"
  default     = "us-docker.pkg.dev/cloudrun/container/hello"
}

variable "min_instances" {
  type        = number
  default     = 0

  validation {
    condition     = var.min_instances >= 0 && var.min_instances <= 1000
    error_message = "min_instances must be between 0 and 1000."
  }
}

variable "max_instances" {
  type        = number
  default     = 5

  validation {
    condition     = var.max_instances >= 1 && var.max_instances <= 1000
    error_message = "max_instances must be between 1 and 1000."
  }
}
