# Generated by infra-x v<version>
# Stack: gcp-cloud-run
# Blueprint: gcp-cloud-run
# Description: Serverless containerized HTTP service on Cloud Run with an Artifact Registry repo for the image.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}
