# Generated by infra-x v<version>
# Stack: aws-eks-cluster
# Blueprint: aws-eks-cluster
# Description: Bare-bones EKS cluster with one managed node group across 2 AZs. Intentionally minimal — bring your own VPC if you need more.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

resource "aws_eks_cluster" "cluster" {
  name     = var.cluster_name
  role_arn = aws_iam_role.cluster_role.arn
  version  = var.kubernetes_version

  vpc_config {
    subnet_ids              = [aws_subnet.subnet_a.id, aws_subnet.subnet_b.id]
    endpoint_public_access  = true
    endpoint_private_access = true
  }
}

resource "aws_eks_node_group" "nodegroup" {
  cluster_name    = aws_eks_cluster.cluster.name
  node_group_name = "${var.cluster_name}-default"
  node_role_arn   = aws_iam_role.node_role.arn
  subnet_ids      = [aws_subnet.subnet_a.id, aws_subnet.subnet_b.id]
  instance_types  = [var.node_instance_type]

  scaling_config {
    desired_size = var.node_desired_size
    min_size     = var.node_min_size
    max_size     = var.node_max_size
  }

  update_config {
    max_unavailable = 1
  }
}
