# Generated by infra-x v<version>
# Stack: aws-eks-cluster
# Blueprint: aws-eks-cluster
# Description: Bare-bones EKS cluster with one managed node group across 2 AZs. Intentionally minimal — bring your own VPC if you need more.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

output "cluster_endpoint" {
  value       = aws_eks_cluster.cluster.endpoint
}

output "cluster_ca" {
  value       = aws_eks_cluster.cluster.certificate_authority[0].data
  sensitive   = true
}

output "kubectl_config_command" {
  value       = "\"aws eks update-kubeconfig --region ${var.aws_region} --name ${var.cluster_name}\""
  description = "Run this locally to point kubectl at the new cluster"
}
