# Generated by infra-x v<version>
# Stack: aws-eks-cluster
# Blueprint: aws-eks-cluster
# Description: Bare-bones EKS cluster with one managed node group across 2 AZs. Intentionally minimal — bring your own VPC if you need more.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

provider "aws" {
  region = "us-east-1"
}
