# Generated by infra-x v<version>
# Stack: aws-eks-cluster
# Blueprint: aws-eks-cluster
# Description: Bare-bones EKS cluster with one managed node group across 2 AZs. Intentionally minimal — bring your own VPC if you need more.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

variable "cluster_name" {
  type        = string

  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9-]{0,99}$", var.cluster_name))
    error_message = "cluster_name must be 1-100 chars, start with a letter, alphanumeric + hyphens only (EKS naming rules)."
  }
}

variable "aws_region" {
  type        = string
  default     = "us-east-1"

  validation {
    condition     = can(regex("^[a-z]{2}-[a-z]+-[0-9]+$", var.aws_region))
    error_message = "aws_region must look like an AWS region (e.g. us-east-1)."
  }
}

variable "kubernetes_version" {
  type        = string
  default     = "1.30"

  validation {
    condition     = can(regex("^1\\.(2[5-9]|3[0-9])$", var.kubernetes_version))
    error_message = "kubernetes_version must be a supported EKS version like \"1.29\", \"1.30\", \"1.31\"."
  }
}

variable "node_instance_type" {
  type        = string
  default     = "t3.medium"
}

variable "node_desired_size" {
  type        = number
  default     = 2

  validation {
    condition     = var.node_desired_size >= 1 && var.node_desired_size <= 1000
    error_message = "node_desired_size must be between 1 and 1000."
  }
}

variable "node_min_size" {
  type        = number
  default     = 1

  validation {
    condition     = var.node_min_size >= 1
    error_message = "node_min_size must be >= 1 (EKS managed node groups require at least 1 node)."
  }
}

variable "node_max_size" {
  type        = number
  default     = 4

  validation {
    condition     = var.node_max_size >= 1 && var.node_max_size <= 1000
    error_message = "node_max_size must be between 1 and 1000."
  }
}
