# Generated by infra-x v<version>
# Stack: aws-eks-cluster
# Blueprint: aws-eks-cluster
# Description: Bare-bones EKS cluster with one managed node group across 2 AZs. Intentionally minimal — bring your own VPC if you need more.
# DO NOT EDIT BY HAND if you plan to regenerate. Use `infra-x regen`.

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}
